### ISSUE TITLE
Pod Problems

### ISSUE THREAD

**Issue by ArEnSc** [drmohundro/SWXMLHash#101]
The pod file brings up 64 errors and causes my app not to compile

**Comment by drmohundro** [comment]
I'm sorry to hear you're running into issues...

* Which version of Xcode are you running?
* Which version are you targeting?
* Did it used to work for you or is this your first time pulling in SWXMLHash?
* Can you provide an example of some of the errors you're seeing?

**Comment by minimartieni** [comment]
Same here, Xcode 8, target: ios 8.0

**Comment by drmohundro** [comment]
@minimartieni I'm sorry to hear that...

* Has it worked in the past and updating to 3.0 started the problems or is this the first time you've integrated SWXMLHash into your app?
* Can you provide an example of the compilation errors you're seeing?

A little more info about what you're running into would help me out a lot.

**Comment by omet** [comment]
Same here
- Cannot invoke 'parse' with an argument list of type '(Data)'
- Cannot invoke 'XMLParser' with an argument list of type '(data: Data)'
- Method  'parse'  cannot be declared public because its parameter uses an internal type
- Cannot invoke 'dataTask' with an argument list of type '(with: URL, completionHandler: (Data?, URLResponse?, Error?) -> Void)'
...

it work in past in Bundle with Alamofire. Now i update to Xcode 8 and compile not work.

**Comment by drmohundro** [comment]
@omet thanks for some additional details, this helps. It sounds like this might be related to Swift 3 conversion (which is new in SWXMLHash 3.0.0). Version 3 converted all `NSData` usages over to `Data`. Which version of SWXMLHash are you referencing in your `Podfile`?

**Comment by omet** [comment]
@drmohundro sorry for long waiting time. With Alamofire comes an very old version with many compile errors. I check some of the versions here and the latest brings the fewest compiler errors (error details in my first post).

**Comment by drmohundro** [comment]
@omet could you paste in your `Podfile` contents? And then paste in the actual snippet of code that is failing to compile?

**Comment by omet** [comment]
No i past no content in my podfile. Alamofire loads your component in dependencies. Compile it many many errors are displayed.

Now i insert the pod manual
pod 'SWXMLHash'
in my podfile and after install amd so on compiler only this errors display

![image](https://cloud.githubusercontent.com/assets/1403618/19391982/260514da-922f-11e6-80eb-f975637aeb5a.png)

**Comment by omet** [comment]
Okay i think i found the problem :) 
I have a

`struct Data {
...
}
`
and this overwrite the Foundation Data Struct you use in for example parse declaration.

Before swift 3 it was no problem. Now I rename my structur and all looks like ok.
Sorry  for your time :)

**Comment by drmohundro** [comment]
@omet ohhhh, yeah, that makes sense. I ran into something similar when I was upgrading SWXMLHash to Swift 3. Thanks for your patience trying to resolve this!

I'm going to go ahead and close this for now then, but if anyone else on this ticket is continuing to have pod issues, please feel free to re-open it.
